version: '2.1'
orbs:
  matlab: mathworks/matlab@0.7
jobs:
  build:
    machine:
      image: 'ubuntu-2004:202111-02'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: myscript
workflows:
  build:
    jobs:
      - build